### ISSUE TITLE
Error on Previewing pages

### ISSUE THREAD

**Issue by marykatefain** [ProjectTIER/projecttier.org#43]
```
File "/vagrant/project_tier/home/templatetags/navigation_tags.py", line 12, in get_site_root
    return context['request'].site.root_page
AttributeError: 'WSGIRequest' object has no attribute 'site'
```

**Comment by alexgleason** [comment]
Error log output below.

Seems to be an issue with the templatetags.

```
2018-12-18T21:47:21.469647+00:00 app[web.1]: Internal Server Error: /admin/pages/191/edit/preview/

2018-12-18T21:47:21.469652+00:00 app[web.1]: Traceback (most recent call last):

2018-12-18T21:47:21.469656+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner

2018-12-18T21:47:21.469657+00:00 app[web.1]:     response = get_response(request)

2018-12-18T21:47:21.469660+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response

2018-12-18T21:47:21.469662+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)

2018-12-18T21:47:21.469663+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response

2018-12-18T21:47:21.469665+00:00 app[web.1]:     response = response.render()

2018-12-18T21:47:21.469683+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 106, in render

2018-12-18T21:47:21.469685+00:00 app[web.1]:     self.content = self.rendered_content

2018-12-18T21:47:21.469687+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content

2018-12-18T21:47:21.469688+00:00 app[web.1]:     content = template.render(context, self._request)

2018-12-18T21:47:21.469690+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render

2018-12-18T21:47:21.469692+00:00 app[web.1]:     return self.template.render(context)

2018-12-18T21:47:21.469693+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 171, in render

2018-12-18T21:47:21.469695+00:00 app[web.1]:     return self._render(context)

2018-12-18T21:47:21.469697+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render

2018-12-18T21:47:21.469699+00:00 app[web.1]:     return self.nodelist.render(context)

2018-12-18T21:47:21.469700+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T21:47:21.469702+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T21:47:21.469704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T21:47:21.469705+00:00 app[web.1]:     return self.render(context)

2018-12-18T21:47:21.469707+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render

2018-12-18T21:47:21.469708+00:00 app[web.1]:     return compiled_parent._render(context)

2018-12-18T21:47:21.469709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render

2018-12-18T21:47:21.469710+00:00 app[web.1]:     return self.nodelist.render(context)

2018-12-18T21:47:21.469712+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T21:47:21.469713+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T21:47:21.469715+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T21:47:21.469716+00:00 app[web.1]:     return self.render(context)

2018-12-18T21:47:21.469717+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render

2018-12-18T21:47:21.469718+00:00 app[web.1]:     return compiled_parent._render(context)

2018-12-18T21:47:21.469720+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render

2018-12-18T21:47:21.469721+00:00 app[web.1]:     return self.nodelist.render(context)

2018-12-18T21:47:21.469722+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T21:47:21.469723+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T21:47:21.469724+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T21:47:21.469725+00:00 app[web.1]:     return self.render(context)

2018-12-18T21:47:21.469727+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render

2018-12-18T21:47:21.469731+00:00 app[web.1]:     result = block.nodelist.render(context)

2018-12-18T21:47:21.469732+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T21:47:21.469733+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T21:47:21.469734+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T21:47:21.469736+00:00 app[web.1]:     return self.render(context)

2018-12-18T21:47:21.469737+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render

2018-12-18T21:47:21.469738+00:00 app[web.1]:     result = block.nodelist.render(context)

2018-12-18T21:47:21.469739+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T21:47:21.469740+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T21:47:21.469741+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T21:47:21.469742+00:00 app[web.1]:     return self.render(context)

2018-12-18T21:47:21.469744+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/library.py", line 214, in render

2018-12-18T21:47:21.469745+00:00 app[web.1]:     _dict = self.func(*resolved_args, **resolved_kwargs)

2018-12-18T21:47:21.469746+00:00 app[web.1]:   File "/app/project_tier/home/templatetags/navigation_tags.py", line 93, in table_of_contents_menu

2018-12-18T21:47:21.469747+00:00 app[web.1]:     'section_pages': section.get_children().specific().live(),


2018-12-18T21:47:21.469755+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'get_children'
```
