### ISSUE TITLE
Cannot create StandardPage beneath HomePage

### ISSUE THREAD

**Issue by alexgleason** [ProjectTIER/projecttier.org#81]
Logs:

```
2018-12-18T23:32:03.677204+00:00 app[web.1]: Internal Server Error: /soup-nuts-exercises/

2018-12-18T23:32:03.677227+00:00 app[web.1]: Traceback (most recent call last):

2018-12-18T23:32:03.677231+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner

2018-12-18T23:32:03.677232+00:00 app[web.1]:     response = get_response(request)

2018-12-18T23:32:03.677234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response

2018-12-18T23:32:03.677236+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)

2018-12-18T23:32:03.677238+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response

2018-12-18T23:32:03.677239+00:00 app[web.1]:     response = response.render()

2018-12-18T23:32:03.677240+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 106, in render

2018-12-18T23:32:03.677241+00:00 app[web.1]:     self.content = self.rendered_content

2018-12-18T23:32:03.677243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content

2018-12-18T23:32:03.677244+00:00 app[web.1]:     content = template.render(context, self._request)

2018-12-18T23:32:03.677246+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render

2018-12-18T23:32:03.677248+00:00 app[web.1]:     return self.template.render(context)

2018-12-18T23:32:03.677249+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 171, in render

2018-12-18T23:32:03.677251+00:00 app[web.1]:     return self._render(context)

2018-12-18T23:32:03.677252+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render

2018-12-18T23:32:03.677253+00:00 app[web.1]:     return self.nodelist.render(context)

2018-12-18T23:32:03.677255+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T23:32:03.677256+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T23:32:03.677257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T23:32:03.677259+00:00 app[web.1]:     return self.render(context)

2018-12-18T23:32:03.677260+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render

2018-12-18T23:32:03.677262+00:00 app[web.1]:     return compiled_parent._render(context)

2018-12-18T23:32:03.677263+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render

2018-12-18T23:32:03.677264+00:00 app[web.1]:     return self.nodelist.render(context)

2018-12-18T23:32:03.677265+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T23:32:03.677267+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T23:32:03.677268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T23:32:03.677269+00:00 app[web.1]:     return self.render(context)

2018-12-18T23:32:03.677270+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render

2018-12-18T23:32:03.677272+00:00 app[web.1]:     return compiled_parent._render(context)

2018-12-18T23:32:03.677273+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render

2018-12-18T23:32:03.677274+00:00 app[web.1]:     return self.nodelist.render(context)

2018-12-18T23:32:03.677275+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T23:32:03.677277+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T23:32:03.677278+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T23:32:03.677279+00:00 app[web.1]:     return self.render(context)

2018-12-18T23:32:03.677280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render

2018-12-18T23:32:03.677282+00:00 app[web.1]:     result = block.nodelist.render(context)

2018-12-18T23:32:03.677283+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T23:32:03.677285+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T23:32:03.677286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T23:32:03.677287+00:00 app[web.1]:     return self.render(context)

2018-12-18T23:32:03.677288+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render

2018-12-18T23:32:03.677289+00:00 app[web.1]:     result = block.nodelist.render(context)

2018-12-18T23:32:03.677290+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 937, in render

2018-12-18T23:32:03.677291+00:00 app[web.1]:     bit = node.render_annotated(context)

2018-12-18T23:32:03.677292+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated

2018-12-18T23:32:03.677293+00:00 app[web.1]:     return self.render(context)

2018-12-18T23:32:03.677295+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/library.py", line 214, in render

2018-12-18T23:32:03.677296+00:00 app[web.1]:     _dict = self.func(*resolved_args, **resolved_kwargs)

2018-12-18T23:32:03.677297+00:00 app[web.1]:   File "/app/project_tier/home/templatetags/navigation_tags.py", line 93, in table_of_contents_menu

2018-12-18T23:32:03.677298+00:00 app[web.1]:     'section_pages': section.get_children().specific().live(),

2018-12-18T23:32:03.677305+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'get_children'
```

**Comment by marykatefain** [comment]
Duplicate with #20
